# Generated by Django 3.1.7 on 2021-04-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orange_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oranges',
            fields=[
                ('orange_id', models.IntegerField(primary_key='True', serialize=False)),
                ('orange_type', models.CharField(max_length=150)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=4)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange_seller.users')),
            ],
        ),
    ]
