# Generated by Django 3.1.7 on 2021-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange_seller', '0003_auto_20210404_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oranges',
            name='rate',
            field=models.CharField(max_length=5),
        ),
    ]
