# Generated by Django 3.1.7 on 2021-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange_seller', '0004_auto_20210404_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.FileField(null='True', upload_to='uploads'),
            preserve_default='True',
        ),
    ]
